language: node_js
node_js:
  - "8"

install:
  - yarn

script:
  - yarn test
  - yarn build

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: public
  target-branch: master
  keep-history: false
  commiter-from-gh: true
  on:
    branch: gatsby
