name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test

      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/gatsby' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: master
          folder: public
